### ISSUE TITLE
alice identity: keybase

### ISSUE THREAD

**Issue by such** [stratumn/go-node#166]
I just wanted to have a discussion here before starting the actual implementation.

Keybase has a concept of proof that we'd use ideally if it supported really custom proofs (see https://keybase.io/docs/api/1.0/call/sig/post). But in the current state of keybase API I don't really see how an Alice proof would fit.

My idea is that we could emulate this concept in Alice.
Basically we'd just have to sign a message, first with our Alice key then with our Keybase key and make it available to others.

To achieve that we could create a keybase service with two gRPC endpoints:

- `Sign`
This would either expect the keybase daemon to be running or take the keybase PGP key path and keybase username as arguments and sign a pb message like:

```
message Identity {
  bytes peer_id = 1;
  string keybase_username = 2;
}

message Proof {
  Identity identity = 1;
  bytes keybase_signature = 2;
  bytes alice_signature = 3;
}
```

Ideally this would be saved in the DHT but we'd have to figure out how to make it somewhat permanent (and revokable?).

- `Lookup`
This would take as argument a keybase username and look for it in the DHT. If found, it would verify the signatures and return the Alice peer_id.

What do you think?

**Comment by t-bast** [comment]
Deprecated.
