### ISSUE TITLE
Indigo Store Alice test network

### ISSUE THREAD

**Issue by t-bast** [stratumn/go-node#192]
We need to setup a test network with automated agents producing links to verify that everything works properly end-to-end over a long period of time (in particular, the sync engine).
There is quite a lot of work to achieve that:
- setup of automated agents simulating a real-life scenario
- deployment
- monitoring to detect bugs

And obviously this will only be needed once we have a stable release candidate.

**Comment by simonvadee** [comment]
I'm closing this since the indigo store has been removed from node.
